### ISSUE TITLE
How to delete all likes related to a post when deleting post?

### ISSUE THREAD

**Issue by Shadecute** [renoki-co/befriended#116]
Thank you for your good package, it works great.
I want to delete the related likes when deleting a post. How is this possible?
I use this method in the model but it does not work!

```
 protected static function boot()
    {
        parent::boot();
        static::deleting(function($model) {
            $model->likers()->delete();
        });
    }
```

**Comment by rennokki** [comment]
I think you want to use the `deleted()` method instead of `deleting()`
