### ISSUE TITLE
[Feature Request] Could you add upvote/downvote features?

### ISSUE THREAD

**Issue by dinhkhanh** [renoki-co/befriended#54]
Hi, 

Thanks for awsome package.

I found your package useful. It will be more useful and maybe will get more uses if it has upvote/downvote features. 

It will be redundant if I write a new package myself because the codebase is similar to current features (Like/Follow,...). 

So, could you add upvote/downvote features to this package?

Thank you,

Khanh

**Comment by Mu9tafa-Online** [comment]
+1 for this feature

**Comment by radudiaconu0** [comment]
Yeah It would me awesome

**Comment by oliuz** [comment]
+1 for this feature
