### ISSUE TITLE
how to fetch my pending request?

### ISSUE THREAD

**Issue by roshani3110** [renoki-co/befriended#75]
hello, 

Can you please help me? 

$user->followerRequests()->count() (this method) gave me my pending requests count. but I need a whole pending request with the user details, can here available for methods that will give Pending requests not pending request count?

**Thanks in Advance!!!**

**Comment by rennokki** [comment]
`followerRequests()` opens up an eloquent query builder via relationship:

```php
$user->followerRequests()->where('accepted', true)->get();
```
