### ISSUE TITLE
how to get all dislikes for a specific topic?

### ISSUE THREAD

**Issue by roshani3110** [renoki-co/befriended#77]
Hello, 

how to get all dislikes for a specific topic? is it available for that method?

$topic->notLikedBy(User::all())->count(); it returns wrong count.

**Thanks..!**

**Comment by rennokki** [comment]
The method exists: https://github.com/renoki-co/befriended/blob/master/src/Scopes/LikeFilterable.php#L39

You should call it for a specific user:

```php
$topic->notLikedBy(User::find(1))->count();
```
