### ISSUE TITLE
Optimize the queries with eager loading

### ISSUE THREAD

**Issue by radudiaconu0** [renoki-co/befriended#81]
So I have the following code

PostResource.php
``` php
public function toArray($request)
 {
       return [
         'author' => new UserResource($this->author),
            'likesCount' => $this->likes_count,
            'isLiked' => $this->is_liked,
           'commentsCount' => $this->comments_count,
           'text' => $this->text,
           'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'id' => $this->id,
       ];
   ` }
```

UserResource.php
``` php 
return [ 
            'id' => $this->id,
            'first_name' => $this->first_name,
            'last_name' => $this->last_name,
            'username' => $this->username,
            'gender' => $this->gender,
            'birthday' => $this->birthday,
            'email' => $this->email,
            'email_verified' => !!$this->email_verified_at,
            'isFollowMe' => $this->isFollowing($authUser),
            'isFollowedByMe' => $authUser->isFollowing($this->resource),
            'isBlockedByMe' => $authUser->isBlocking($this->resource),
            'followersCount' => $this->followers_count,
            'followingCount' => $this->following_count
        ];
```

PostController.php

```php
public function index()
    {
        $user = Auth::user();
        $followersPost = Post
            ::with(['author' => function ($query) {
                $query->withCount('followers', 'following');
            }])->withCount('comments', 'likes')
            ->whereHas('author', function ($query) use ($user) {
                $query->followedBy($user);
            })
            ->orWhere('author_id', $user->id)
            ->latest()
            ->paginate(7);
        return PostResource::collection($followersPost);
    }
```

Is there a method to optimize the queries? I mean it does 18 queries just for 3 posts ;( . I tried to search on google but find nothing

**Comment by rennokki** [comment]
@radudiaconu0 This is intended for a small-medium scale. You can pair it up with https://github.com/renoki-co/laravel-eloquent-query-cache as you might want to cache them.

For a medium-large scale, you should try using Neo4j or any graph database.

**Comment by radudiaconu0** [comment]
@rennokki   Yeah i know . I just wanted to know if I can somehow solve the N+1 problem. If I can reduce the queries somehow.

**Comment by radudiaconu0** [comment]
I do something wrong in my code? Can I write it more optimal?

**Comment by rennokki** [comment]
Can you run `->dd()` before `->paginate()` and show me the dumped output?

**Comment by radudiaconu0** [comment]
"select `posts`.*, (select count(*) from `comments` where `posts`.`id` = `comments`.`post_id`) as `comments_count`, (select count(*) from `users` inner join `likers` on
`users`.`id` = `likers`.`liker_id` where `posts`.`id` = `likers`.`likeable_id` and `likers`.`likeable_type` = ? and `likers`.`liker_type` = ? and `likers`.`likeable_type
` = ?) as `likes_count` from `posts` where exists (select * from `users` where `posts`.`author_id` = `users`.`id` and `id` in (?)) or `author_id` = ? order by `created_a
t` desc"
array:5 [
  0 => "App\Models\Post"
  1 => "App\Models\User"
  2 => "App\Models\Post"
  3 => 1
  4 => 1
]

**Comment by radudiaconu0** [comment]
![image](https://user-images.githubusercontent.com/52667211/101362064-4e0bf600-38a8-11eb-8f61-920efabdf576.png)

**Comment by rennokki** [comment]
It seems like there are 4 queries.

**Comment by radudiaconu0** [comment]
yeah because it is not wrapped into PostResource

**Comment by radudiaconu0** [comment]
You in PostResource i have a lot of  relationships
