### ISSUE TITLE
[question] Is it possible to filtering liked content by model type

### ISSUE THREAD

**Issue by ClementN** [renoki-co/befriended#82]
Hello,

Thank you for your work on this package.

Is it possible to filter the liked content by model type when multiple models are likable? 

Eg.. if user and pages are likable, is it possible to get only pages liked by Bob?

**Comment by rennokki** [comment]
There is an example for each case in the documentation. Basically, you can pass a parameter to the `likes` with the class:

```php
$user->likes(Page::class)->count();
```

[See more about the liking examples](https://github.com/renoki-co/befriended#liking)

**Comment by code23-isaac** [comment]
Is it possible to provide multiple classes to the `likers()` method, or do these have to be separate queries?

Would be great to get back all the models of all types in one go

**Comment by rennokki** [comment]
They have to be separate queries since the relation beneath is morph.
